"""``massingviser.kernel`` -- the permanent backbone.

The kernel contains *mechanisms*, never features. Nothing in this package knows what an IFC model,
a markup pin, a massing story or a cost assembly is. Capability arrives only through plugins, which
is what allows the kernel to be versioned and held stable.
"""

from .capabilities import (
    CapabilityProvider,
    CapabilityRegistry,
    CapabilityToken,
    create_capability_token,
)
from .commands import (
    CommandBus,
    CommandDefinition,
    CommandExecutionContext,
    CommandInfo,
    CommandInvocation,
    CommandMiddleware,
)
from .container import (
    ServiceContainer,
    ServiceFactory,
    ServiceLifetime,
    ServiceToken,
    create_service_token,
)
from .container_format import (
    ContainerAdapter,
    ContainerAdapterOptions,
    ContainerCreateInit,
    ContainerEntry,
    ContainerManifest,
    ContainerService,
    ContainerSource,
    InMemoryContainer,
    OpenContainer,
    StorageContainerAdapter,
)
from .disposable import NOOP_DISPOSABLE, Disposable, DisposableStore, to_disposable
from .errors import KernelError, KernelErrorCode, to_kernel_error
from .events import EmitReport, EventBus, EventHandler
from .kernel import (
    KERNEL_API_VERSION,
    CapabilityRegistryToken,
    CommandBusToken,
    ContainerServiceToken,
    EventBusToken,
    Kernel,
    KernelDiagnostics,
    LoggerToken,
    PermissionsToken,
    PersistenceToken,
    StateStoreToken,
    TelemetryToken,
    create_kernel,
)
from .logging import Logger, LogLevel, create_logger
from .permissions import (
    ALLOW_ALL,
    ANONYMOUS_IDENTITY,
    Identity,
    PermissionEvaluator,
    PermissionRequest,
    PermissionService,
    create_role_evaluator,
)
from .persistence import (
    BackupEntry,
    DocumentMigrator,
    MemoryStorageAdapter,
    NamespacedPersistence,
    PersistenceEngine,
    StorageAdapter,
    VersionedDocument,
    is_versioned_document,
)
from .plugin_host import (
    ActivationReport,
    Plugin,
    PluginCapabilities,
    PluginCommands,
    PluginContext,
    PluginDependency,
    PluginEvents,
    PluginHost,
    PluginManifest,
    PluginRecord,
    PluginState,
    PluginStatus,
    PluginUI,
)
from .result import (
    Err,
    Ok,
    Result,
    attempt,
    attempt_async,
    err,
    is_err,
    is_ok,
    map_err,
    map_ok,
    ok,
    unwrap,
    unwrap_or,
)
from .semver import SemVer, compare_semver, parse_semver, satisfies
from .state import Slice, StateChange, StateListener, StateStore, same_value
from .telemetry import (
    NOOP_TELEMETRY,
    CompositeTelemetrySink,
    InMemoryTelemetrySink,
    NoopTelemetrySink,
    TelemetryRecord,
    TelemetrySink,
    TelemetryTags,
)
from .ui_registry import (
    UIContribution,
    UIContributionPoint,
    UIExtensionRegistry,
    UIMountContext,
)

__all__ = [
    "ALLOW_ALL",
    "ANONYMOUS_IDENTITY",
    "ActivationReport",
    "BackupEntry",
    "CapabilityProvider",
    "CapabilityRegistry",
    "CapabilityRegistryToken",
    "CapabilityToken",
    "CommandBus",
    "CommandBusToken",
    "CommandDefinition",
    "CommandExecutionContext",
    "CommandInfo",
    "CommandInvocation",
    "CommandMiddleware",
    "CompositeTelemetrySink",
    "ContainerAdapter",
    "ContainerAdapterOptions",
    "ContainerCreateInit",
    "ContainerEntry",
    "ContainerManifest",
    "ContainerService",
    "ContainerServiceToken",
    "ContainerSource",
    "Disposable",
    "DisposableStore",
    "DocumentMigrator",
    "EmitReport",
    "Err",
    "EventBus",
    "EventBusToken",
    "EventHandler",
    "Identity",
    "InMemoryContainer",
    "InMemoryTelemetrySink",
    "KERNEL_API_VERSION",
    "Kernel",
    "KernelDiagnostics",
    "KernelError",
    "KernelErrorCode",
    "LogLevel",
    "Logger",
    "LoggerToken",
    "MemoryStorageAdapter",
    "NOOP_DISPOSABLE",
    "NOOP_TELEMETRY",
    "NamespacedPersistence",
    "NoopTelemetrySink",
    "Ok",
    "OpenContainer",
    "PermissionEvaluator",
    "PermissionRequest",
    "PermissionService",
    "PermissionsToken",
    "PersistenceEngine",
    "PersistenceToken",
    "Plugin",
    "PluginCapabilities",
    "PluginCommands",
    "PluginContext",
    "PluginDependency",
    "PluginEvents",
    "PluginHost",
    "PluginManifest",
    "PluginRecord",
    "PluginState",
    "PluginStatus",
    "PluginUI",
    "Result",
    "SemVer",
    "ServiceContainer",
    "ServiceFactory",
    "ServiceLifetime",
    "ServiceToken",
    "Slice",
    "StateChange",
    "StateListener",
    "StateStore",
    "StateStoreToken",
    "StorageAdapter",
    "StorageContainerAdapter",
    "TelemetryRecord",
    "TelemetrySink",
    "TelemetryTags",
    "TelemetryToken",
    "UIContribution",
    "UIContributionPoint",
    "UIExtensionRegistry",
    "UIMountContext",
    "VersionedDocument",
    "attempt",
    "attempt_async",
    "compare_semver",
    "create_capability_token",
    "create_kernel",
    "create_logger",
    "create_role_evaluator",
    "create_service_token",
    "err",
    "is_err",
    "is_ok",
    "is_versioned_document",
    "map_err",
    "map_ok",
    "ok",
    "parse_semver",
    "same_value",
    "satisfies",
    "to_disposable",
    "to_kernel_error",
    "unwrap",
    "unwrap_or",
]
