"""ICDD -- ISO 21597 Information Container for linked Document Delivery, both parts.

ZIP is a port and validation is structural rather than SHACL; both boundaries are documented in
``container``. Known limits: RDF/XML only (no Turtle or JSON-LD), ``rdf:parseType`` and DTDs are
refused rather than mis-parsed, and checksums are not verified.
"""

from .container import (
    Container,
    ContainerArchive,
    ContainerDescription,
    Document,
    DocumentKind,
    Identifier,
    IdentifierKind,
    Link,
    LinkElement,
    Linkset,
    MemoryArchive,
    Party,
    PartyKind,
    ValidationIssue,
    ValidationReport,
    build_index_graph,
    build_linkset_graph,
    invert_link,
    validate_container,
    write_container,
)
from .ontology import (
    CONTAINER_LAYOUT,
    CT,
    DEFAULT_PREFIXES,
    LINK_TYPES,
    LS,
    NS,
    ONTOLOGY_IRI,
    LinkFamily,
    LinkTypeDescriptor,
    link_type_by_iri,
)
from .plugin import ICDD_COMMANDS, PLUGIN_ID, IcddToken, create_icdd_plugin, icdd_plugin
from .rdf import Graph, Iri, Literal, RdfError, Triple, parse, serialise

__all__ = [
    "CONTAINER_LAYOUT",
    "CT",
    "DEFAULT_PREFIXES",
    "ICDD_COMMANDS",
    "LINK_TYPES",
    "LS",
    "NS",
    "ONTOLOGY_IRI",
    "PLUGIN_ID",
    "Container",
    "ContainerArchive",
    "ContainerDescription",
    "Document",
    "DocumentKind",
    "Graph",
    "IcddToken",
    "Identifier",
    "IdentifierKind",
    "Iri",
    "Link",
    "LinkElement",
    "LinkFamily",
    "LinkTypeDescriptor",
    "Linkset",
    "Literal",
    "MemoryArchive",
    "Party",
    "PartyKind",
    "RdfError",
    "Triple",
    "ValidationIssue",
    "ValidationReport",
    "build_index_graph",
    "build_linkset_graph",
    "create_icdd_plugin",
    "icdd_plugin",
    "invert_link",
    "link_type_by_iri",
    "parse",
    "serialise",
    "validate_container",
    "write_container",
]
