/**
 * The JavaScript reader, tested against buffers the *Python* encoder wrote.
 *
 * That is the whole point of these tests. A JS test using a JS-built fixture proves the reader
 * agrees with itself; the fixtures here are generated by `massingviser.geometry.payload` and
 * checked in, so a change to either side that breaks the contract fails here.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  MeshFormatError,
  decodeMeshBatch,
  indexManifest,
  planTransfer,
  selectLod,
} from '../src/mvmesh.js';

const here = dirname(fileURLToPath(import.meta.url));
const fixtures = join(here, 'fixtures');

function load(name) {
  const data = readFileSync(join(fixtures, name));
  return data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength);
}

const manifest = JSON.parse(readFileSync(join(fixtures, 'manifest.json'), 'utf8'));

test('a shaded cube decodes to the geometry Python encoded', () => {
  const { lod, meshes } = decodeMeshBatch(load('cube-shaded.bin'));
  assert.equal(lod, 0);
  assert.equal(meshes.length, 1);
  const [cube] = meshes;
  // 24 vertices: every corner of a box creases, so each of the 8 is split three ways.
  assert.equal(cube.positions.length, 24 * 3);
  assert.equal(cube.indices.length, 12 * 3);
  assert.ok(cube.normals, 'the payload declared normals');
  assert.equal(cube.normals.length, 24 * 3);
});

test('normals arrive unit length and axis aligned for a box', () => {
  const { meshes } = decodeMeshBatch(load('cube-shaded.bin'));
  const { normals } = meshes[0];
  for (let index = 0; index < normals.length; index += 3) {
    const [x, y, z] = [normals[index], normals[index + 1], normals[index + 2]];
    assert.ok(Math.abs(Math.hypot(x, y, z) - 1) < 1e-5, 'unit length');
    assert.ok(Math.abs(Math.abs(x) + Math.abs(y) + Math.abs(z) - 1) < 1e-5, 'axis aligned');
  }
});

test('an unshaded payload reports no normals rather than inventing them', () => {
  const { meshes } = decodeMeshBatch(load('cube-plain.bin'));
  assert.equal(meshes[0].normals, null);
  assert.equal(meshes[0].positions.length, 8 * 3);
});

test('positions are the metres Python wrote', () => {
  const { meshes } = decodeMeshBatch(load('cube-plain.bin'));
  const xs = [];
  for (let index = 0; index < meshes[0].positions.length; index += 3) {
    xs.push(meshes[0].positions[index]);
  }
  assert.equal(Math.min(...xs), 0);
  assert.equal(Math.max(...xs), 1);
});

test('indices are local to their mesh, so an element uploads without rebasing', () => {
  const { meshes } = decodeMeshBatch(load('two-cubes.bin'));
  assert.equal(meshes.length, 2);
  for (const mesh of meshes) {
    const vertices = mesh.positions.length / 3;
    assert.ok(Math.max(...mesh.indices) < vertices, 'no index escapes its own mesh');
  }
});

test('the second mesh in a chunk is offset in space, not in index', () => {
  const { meshes } = decodeMeshBatch(load('two-cubes.bin'));
  assert.equal(meshes[0].positions[0], 0);
  assert.equal(meshes[1].positions[0], 10);
});

test('a version 1 payload still reads, without normals', () => {
  const { meshes } = decodeMeshBatch(load('cube-v1.bin'));
  assert.equal(meshes[0].normals, null);
});

test('something that is not a payload is refused', () => {
  const buffer = new ArrayBuffer(64);
  new DataView(buffer).setUint32(0, 0x46544c47, true); // "GLTF"
  assert.throws(() => decodeMeshBatch(buffer), MeshFormatError);
});

test('a truncated payload is refused rather than misread', () => {
  const full = load('cube-shaded.bin');
  assert.throws(() => decodeMeshBatch(full.slice(0, full.byteLength - 4)), MeshFormatError);
});

test('a future version is refused rather than guessed at', () => {
  const buffer = load('cube-shaded.bin').slice(0);
  new DataView(buffer).setUint32(4, 99, true);
  assert.throws(() => decodeMeshBatch(buffer), /this build reads/);
});

test('the manifest indexes every drawable node by GlobalId', () => {
  const { byGlobalId, payloads } = indexManifest(manifest);
  assert.ok(byGlobalId.size > 0);
  for (const node of byGlobalId.values()) {
    for (const level of node.geometry) {
      assert.ok(payloads.has(level.payloadId), 'every ladder entry names a declared payload');
    }
  }
});

test('a ladder is ordered finest first', () => {
  const { byGlobalId } = indexManifest(manifest);
  for (const node of byGlobalId.values()) {
    const levels = node.geometry.map((level) => level.lod);
    assert.deepEqual(levels, [...levels].sort((a, b) => a - b));
  }
});

test('LOD selection walks down the ladder with distance and clamps at both ends', () => {
  const ladder = [
    { lod: 0, faceCount: 900 },
    { lod: 1, faceCount: 200 },
    { lod: 2, faceCount: 40 },
  ];
  assert.equal(selectLod(ladder, 0).lod, 0);
  assert.equal(selectLod(ladder, 70).lod, 1);
  assert.equal(selectLod(ladder, 5000).lod, 2, 'clamps to the coarsest it has');
  assert.equal(selectLod([], 10), null);
});

test('a node with one level always resolves to that level', () => {
  const ladder = [{ lod: 0, faceCount: 12 }];
  assert.equal(selectLod(ladder, 10_000).lod, 0);
});

test('the client-side transfer plan agrees with the server', () => {
  // Same set difference `engine.scene.plan` computes; the fixture records the server's answer.
  const plan = planTransfer(manifest.payloads, []);
  assert.equal(plan.fetch.length, manifest.payloads.length);
  assert.deepEqual(plan.reuse, []);

  const all = manifest.payloads.map((payload) => payload.id);
  const warm = planTransfer(manifest.payloads, all);
  assert.deepEqual(warm.fetch, []);
  assert.deepEqual(warm.reuse, [...all].sort());

  const stale = planTransfer(manifest.payloads, [...all, 'c'.repeat(32)]);
  assert.deepEqual(stale.stale, ['c'.repeat(32)]);
});
